main: org.meekers.plugins.meekarena.MeekArena
name: MeekArena
version: 1.0
author: Jared Meeker
description: Generate a PVP arena

commands:
   arena:
      description: MeekArena Commands
      usage: /<command> [start | stop | status | join | leave]